[package]
name = "r2"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["r2 contributors"]
license = "MIT"
description = "LaTeX-like minimalist template for academic papers and presentation slides"
categories = ["paper", "presentation"]
keywords = ["academic", "paper", "slides", "polylux", "template"]
repository = "https://github.com/shusuke-ioku/r2-typst"

[template]
path = "template"
entrypoint = "paper.typ"
thumbnail = "thumbnail.png"
